name: master

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'      
  workflow_dispatch:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

jobs:
  build:
    name: Build
    if: github.event_name == 'push' && contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    runs-on: ubuntu-latest
    env: 
      working-directory: ./src 
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.working-directory}}
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ${{env.working-directory}}
    - name: Publish win-x64
      run:  dotnet publish -p:PublishProfile=winx64
      working-directory: ${{env.working-directory}}
    - name: Publish linux-x64
      run:  dotnet publish -p:PublishProfile=linuxx64
      working-directory: ${{env.working-directory}}
    - name: Publish osx-x64
      run:  dotnet publish -p:PublishProfile=osxx64
      working-directory: ${{env.working-directory}}
    - name: Upload win-x64 artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: win-x64
        path: /home/runner/work/msgtool/msgtool/src/azmsg/bin/Release/net5.0/publish/win-x64/
    - name: Upload linuxx64 artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: linux-x64
        path: /home/runner/work/msgtool/msgtool/src/azmsg/bin/Release/net5.0/publish/linux-x64/       
    - name: Upload osx-x64 artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: osx-x64
        path: /home/runner/work/msgtool/msgtool/src/azmsg/bin/Release/net5.0/publish/osx-x64/
      

